/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectocs;

/**
 *
 * @author Usuario
 */
public class Frm_Validador_id extends javax.swing.JFrame {
    private int numerovalidador;
    /**
     * Creates new form Frm_Validador_cedula
     */
    public Frm_Validador_id() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Iddoctor = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_Proceder = new javax.swing.JButton();
        btn_volvermenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_imagen = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Iddoctor.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lbl_Iddoctor.setText("Ingrese el id:");
        jPanel1.add(lbl_Iddoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 360, 50));

        btn_Proceder.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btn_Proceder.setText("PROCEDER");
        btn_Proceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProcederActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Proceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 120, 40));

        btn_volvermenu.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btn_volvermenu.setText("VOLVER");
        btn_volvermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volvermenuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volvermenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 120, 40));

        jPanel3.setBackground(new java.awt.Color(158, 219, 240));

        lbl_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contents/libretaconlupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(lbl_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(lbl_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 290, 360));

        jPanel4.setBackground(new java.awt.Color(158, 219, 240));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 40, 50));

        jPanel5.setBackground(new java.awt.Color(158, 219, 240));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int getNumerovalidador() {
        return numerovalidador;
    }

    public void setNumerovalidador(int numerovalidador) {
        this.numerovalidador = numerovalidador;
    }
    
    
    private void btn_ProcederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProcederActionPerformed
        // TODO add your handling code here:
        manejodearchivosDOCTOR obj_doctor = new manejodearchivosDOCTOR();
        String id = txt_id.getText();
        obj_doctor.setId(id);

        if(numerovalidador == 1){
            //eliminar doc
            obj_doctor.eliminaDoctor();
        }
        if(numerovalidador == 2){
            //actualizardoc
            obj_doctor.editarDoctor();
        }
        if(numerovalidador == 3){
            //eliminar pac
            
        }
        if(numerovalidador == 4){
            //actualizar pac
            
        }

        limpiador();
    }//GEN-LAST:event_btn_ProcederActionPerformed

    public void limpiador(){
        txt_id.setText("");
    }
    private void btn_volvermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volvermenuActionPerformed
        // TODO add your handling code here:
         Frm_Menudoctor doc = new Frm_Menudoctor();
         this.dispose();
         doc.setLocationRelativeTo(null);
         doc.setVisible(true);
    }//GEN-LAST:event_btn_volvermenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Validador_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Validador_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Validador_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Validador_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Validador_id().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Proceder;
    private javax.swing.JButton btn_volvermenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_Iddoctor;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
